version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    # command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik

    # build: .
    depends_on:
      - db


  db:
    image: postgres:latest
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

volumes:
  postgres-volume:


    # volumes:
    #   - ./:/code:ro
    # environment:
    #   - DATABASE_URL=postgresql://postgres:Bright#1270@localhost:5433/dockert
    # ports:
    #   - "8000:80"

#   db:
#       image: postgres:latest
#       volumes:
#         - postgres-volume:/var/lib/postgresql/data/
#       expose:
#         - 5433
#       environment:
#         - POSTGRES_USER=postgres
#         - POSTGRES_PASSWORD=Bright#1270
#         - POSTGRES_DB=dockert

# volumes:
#       postgres-volume: 
